### PR TITLE
Refactor to ESM

### LINKED ISSUE #4: Plugin updates
@maltsev @Scrum I'd like to work on a major release for this plugin if you're OK with it:

- ESM, no build step
- update dependencies
- update build and ci
- `stringifyAttr || true` in `parser.es6` so it doesn't quote attributes on its own

Using it in a bunch of plugins and in Maizzle, it has been really useful 🙏

### PR DESCRIPTION
**Pull request by cossssmin**
This PR updates the plugin to ESM and also updates dependencies.

- [x] require Node.js 16+
- [x] ESM-only, no build step
- [x] updated dependencies

New features:

- [x] moved tests to vitest
- [x] added GitHub Actions build workflow
- [x] added dependabot for automated dependency updates
- [x] added `np` for publishing releases
- [x] stop quoting empty/no-value attributes

These updates include breaking changes, so we'll need to publish `v1.0.0`.

Closes #4

### CODE REVIEW

**Comment by cossssmin** [comment]
@maltsev @Scrum if this looks good to you I'll go ahead and merge it, then release `v1.0.0` 👍

**Review by Scrum — APPROVED** [review]

**Comment by cossssmin** [comment]
Just realized I need to update CHANGELOG.md, doing it now...

**Comment by maltsev** [comment]
Looks good! Thanks a lot for refactoring it!

**Comment by cossssmin** [comment]
Thanks, I'll update the readme and changelog and then we can release `v1.0.0` 👍

**Pull request merged**
