### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by cossssmin**
Updated changelog and readme.

### CODE REVIEW

**Comment by cossssmin** [comment]
@maltsev @Scrum merging this and releasing `v1.0.0` 🥳

**Comment by cossssmin** [comment]
I don't have the NPM permissions to publish it, please publish `v1.0.0` when you can (ideally with `npm run release` so we get the nice auto-generated release notes) or add `cossssmin` to the NPM collaborators for this package. Thanks!

**Comment by maltsev** [comment]
Thanks! I published it.

> so we get the nice auto-generated release notes

It generated just a list of commits between two versions. I think it's better to use the release notes from `CHANGELOG.md`.

**Comment by cossssmin** [comment]
Thanks! 

> It generated just a list of commits between two versions. I think it's better to use the release notes from `CHANGELOG.md`.

Agree, as long as we remember to write release notes so people using tools like Dependabot/depfu can click to see what changed 👍

**Comment by cossssmin** [comment]
And just found a bug with the new feature I added, fixing... :)

**Pull request merged**
